export type MemeLanguage = 'brainrot' | 'simlish' | 'pirate'

export interface TranslatorOption {
  id: MemeLanguage
  label: string
  emoji: string
}

export const TRANSLATOR_OPTIONS: TranslatorOption[] = [
  { id: 'brainrot', label: 'Brainrot', emoji: '🧠' },
  { id: 'simlish', label: 'Simlish', emoji: '💎' },
  { id: 'pirate', label: 'Pirate', emoji: '🏴‍☠️' },
]

type Dict = [RegExp, string][]

function buildDict(entries: [string, string][]): Dict {
  // Sort longest-first to avoid partial matches
  const sorted = [...entries].sort((a, b) => b[0].length - a[0].length)
  return sorted.map(([pattern, replacement]) => [
    new RegExp(`\\b${pattern}\\b`, 'gi'),
    replacement,
  ])
}

function applyDict(text: string, dict: Dict): string {
  let result = text
  for (const [regex, replacement] of dict) {
    result = result.replace(regex, replacement)
  }
  return result
}

const brainrotDict = buildDict([
  ['students', 'the squad'],
  ['student', 'lil bro'],
  ['teacher', 'main character'],
  ['teachers', 'main characters'],
  ['classroom', 'the vibe zone'],
  ['classrooms', 'vibe zones'],
  ['school', 'the grind'],
  ['schools', 'the grinds'],
  ['learning', 'locking in'],
  ['learn', 'lock in'],
  ['education', 'the lore'],
  ['help', 'be a real one for'],
  ['helping', 'being a real one for'],
  ['donate', 'throw some bread at'],
  ['donation', 'bread toss'],
  ['donations', 'bread tosses'],
  ['money', 'bread'],
  ['fund', 'rizz up'],
  ['funding', 'rizzing up'],
  ['funded', 'rizzed up'],
  ['amazing', 'bussin fr fr'],
  ['awesome', 'absolutely goated'],
  ['wonderful', 'lowkey iconic'],
  ['great', 'fire'],
  ['excellent', 'no cap elite'],
  ['need', 'are cooked without'],
  ['needed', 'were cooked without'],
  ['needs', 'is cooked without'],
  ['books', 'the sacred texts'],
  ['book', 'sacred text'],
  ['science', 'no cap science'],
  ['math', 'math (its giving struggle)'],
  ['reading', 'main quest'],
  ['community', 'the group chat'],
  ['support', 'carry'],
  ['supporting', 'carrying'],
  ['children', 'the younglings'],
  ['kids', 'mini humans'],
  ['project', 'the vibe check'],
  ['projects', 'vibe checks'],
  ['technology', 'the WiFi arts'],
  ['supplies', 'the loot'],
  ['thank you', 'you ate that'],
  ['thanks', 'slay'],
  ['grateful', 'lowkey blessed'],
  ['excited', 'hyped no cap'],
  ['important', 'main character energy'],
  ['experience', 'character arc'],
  ['opportunity', 'W moment'],
  ['inspire', 'give rizz to'],
  ['inspiring', 'giving rizz'],
  ['dream', 'roman empire'],
  ['dreams', 'roman empires'],
  ['love', 'absolutely stan'],
  ['creative', 'built different'],
  ['succeed', 'pass the vibe check'],
  ['success', 'W'],
  ['goal', 'the mission'],
  ['goals', 'the missions'],
  ['future', 'the endgame'],
  ['together', 'on gang'],
  ['believe', 'no cap trust'],
  ['special', 'lowkey legendary'],
  ['happy', 'vibing'],
  ['please', 'pls fr'],
  ['every', 'literally every'],
  ['really', 'deadass'],
  ['very', 'mad'],
])

const simlishDict = buildDict([
  ['hello', 'sul sul'],
  ['hi', 'sul sul'],
  ['goodbye', 'dag dag'],
  ['bye', 'dag dag'],
  ['thank you', 'ba-deesh'],
  ['thanks', 'ba-deesh'],
  ['yes', 'ooh be gah'],
  ['no', 'besnay'],
  ['money', 'simoleons'],
  ['love', 'nooboo'],
  ['school', 'blarbzit'],
  ['teacher', 'florgit'],
  ['teachers', 'florgits'],
  ['students', 'narbleflops'],
  ['student', 'narbleflop'],
  ['help', 'meshaloob'],
  ['helping', 'meshalooping'],
  ['learn', 'zeeplewhop'],
  ['learning', 'zeeplewopping'],
  ['books', 'gerbits'],
  ['book', 'gerbit'],
  ['classroom', 'frabble zonk'],
  ['classrooms', 'frabble zonks'],
  ['need', 'wabadoo'],
  ['needs', 'wabadoos'],
  ['great', 'ooh wee'],
  ['please', 'zagga'],
  ['want', 'meshla'],
  ['happy', 'firby'],
  ['sad', 'sulsul noo'],
  ['friend', 'snorble'],
  ['friends', 'snorbles'],
  ['donate', 'flibble-floo'],
  ['donation', 'flibble-floo'],
  ['children', 'bloobie-doos'],
  ['kids', 'bloobie-doos'],
  ['project', 'worp-worp'],
  ['projects', 'worp-worps'],
  ['community', 'za plorg'],
  ['family', 'bloo bagoo'],
  ['science', 'zimzam'],
  ['math', 'noombers'],
  ['reading', 'squibble-dee'],
  ['technology', 'beep borp'],
  ['supplies', 'flimflam bits'],
  ['support', 'skoodlypoop'],
  ['amazing', 'zowee wowee'],
  ['wonderful', 'wubba nubba'],
  ['awesome', 'hooba noobie'],
  ['good', 'goob'],
  ['experience', 'flooba-dee'],
  ['opportunity', 'snazzle-pop'],
  ['education', 'za big zeeple'],
  ['future', 'za nex-nex'],
  ['success', 'woohoo'],
  ['dream', 'snoozle wish'],
  ['dreams', 'snoozle wishes'],
  ['inspire', 'sparkle-floo'],
  ['exciting', 'fizzy-pop'],
  ['creative', 'artsy-fartsy'],
  ['together', 'snuggle-bunch'],
  ['the', 'za'],
  ['and', 'en'],
  ['with', 'wif'],
  ['for', 'flor'],
  ['this', 'zis'],
  ['that', 'zat'],
])

const pirateDict = buildDict([
  ['hello', 'ahoy'],
  ['hi', 'ahoy'],
  ['students', 'young scallywags'],
  ['student', 'young scallywag'],
  ['teacher', "the cap'n"],
  ['teachers', "the cap'ns"],
  ['classroom', "the ship's quarters"],
  ['classrooms', "the ships' quarters"],
  ['school', "the academy o' the seven seas"],
  ['schools', 'the academies'],
  ['money', 'doubloons'],
  ['dollar', 'doubloon'],
  ['dollars', 'doubloons'],
  ['donate', 'plunder yer coffers fer'],
  ['donation', 'treasure offering'],
  ['donations', 'treasure offerings'],
  ['help', 'lend a hook to'],
  ['helping', 'lendin a hook to'],
  ['books', "the captain's logs"],
  ['book', "the captain's log"],
  ['learn', 'chart the waters of'],
  ['learning', 'chartin the waters of'],
  ['education', "seafarin' wisdom"],
  ['need', 'be in dire need of'],
  ['needs', 'be in dire need of'],
  ['thank you', 'ye have me gratitude'],
  ['thanks', 'much obliged, matey'],
  ['my', 'me'],
  ['your', 'yer'],
  ['you', 'ye'],
  ['is', 'be'],
  ['are', 'be'],
  ['was', 'were'],
  ['project', 'expedition'],
  ['projects', 'expeditions'],
  ['technology', 'modern contraptions'],
  ['science', 'the dark arts of nature'],
  ['math', 'navigational reckonin'],
  ['reading', "readin' the ancient scrolls"],
  ['supplies', 'provisions'],
  ['community', 'the crew'],
  ['children', 'the wee ones'],
  ['kids', 'the wee ones'],
  ['family', 'the clan'],
  ['support', 'rally behind'],
  ['supporting', 'rallyin behind'],
  ['amazing', 'shiver me timbers'],
  ['wonderful', 'mighty fine'],
  ['awesome', 'blimey magnificent'],
  ['great', 'grand'],
  ['good', 'fine'],
  ['fund', 'fill the coffers for'],
  ['funding', 'fillin the coffers for'],
  ['funded', 'the coffers be full for'],
  ['dream', 'treasure map'],
  ['dreams', 'treasure maps'],
  ['future', 'the horizon ahead'],
  ['success', 'glory'],
  ['experience', 'voyage'],
  ['opportunity', 'fair winds'],
  ['inspire', 'stir the spirit of'],
  ['exciting', 'swashbucklin'],
  ['creative', 'crafty as a fox'],
  ['together', 'crew united'],
  ['happy', 'jolly'],
  ['please', 'if ye please'],
  ['friend', 'matey'],
  ['friends', 'mateys'],
  ['love', 'have a mighty fondness fer'],
  ['want', 'be seekin'],
  ['home', 'port'],
  ['work', 'toil'],
  ['working', 'toilin'],
])

export function translate(text: string, language: MemeLanguage): string {
  switch (language) {
    case 'brainrot':
      return applyDict(text, brainrotDict)
    case 'simlish':
      return applyDict(text, simlishDict)
    case 'pirate':
      return applyDict(text, pirateDict)
  }
}
